from argparse import ArgumentParser
from torch.cuda import device_count
from torch.multiprocessing import spawn

from learner import train, train_distributed
from params import params

def _get_free_port():
  import socketserver
  with socketserver.TCPServer(('localhost', 0), None) as s:
    return s.server_address[1]


def main(args):
  replica_count = device_count()
  if replica_count > 1:
    if params.batch_size % replica_count != 0:
      raise ValueError(f'Batch size {params.batch_size} is not evenly divisble by # GPUs {replica_count}.')
    params.batch_size = params.batch_size // replica_count
    port = _get_free_port()
    spawn(train_distributed, args=(replica_count, port, args, params), nprocs=replica_count, join=True)
  else:
    train(args, params)


if __name__ == '__main__':
    parser = ArgumentParser(description='train (or resume training) a DiffWave model')
    parser.add_argument('--model_dir', default='model_dir/default_experiment',
                        help='directory in which to store model checkpoints and training logs')
    parser.add_argument('--gt_dir', default='data/gt/',
                        help='clean directory')
    parser.add_argument('--chrom_dir', default='data/noisy/',
                        help='noisy directory')
    parser.add_argument('--data_dirs', nargs='+', default=['data/spectrogram/'],
                        help='space separated list of directories from spectrogram file generated by diffwave.preprocess')
    parser.add_argument('--max_steps', default=9030, type=int,
                        help='maximum number of training steps')
    parser.add_argument('--fp16', action='store_true', default=False,
                        help='use 16-bit floating point operations for training')
    main(parser.parse_args())

